#!/usr/bin/env bash
# bench_ab_post_build.sh — auto-bench harness exercised after a fresh pod build.
#
# Exercises three landed-this-session improvements:
#   - GAP-B   : `dsv4_route_kernel` block-parallel rewrite (bc068c93)
#   - GAP-C-c : FP8 decode cp.async pipeline (9ffaa622 / ab850f7a content)
#   - INT4 KIVI two-level-K + asymmetric [-8,7] (9ca4dbb4)
#
# Compares HEAD vs `--baseline-ref` parent (default: previous HEAD~N) and emits
# Δ% TPOT / mean_match deltas to `docs/experience/wins/`. Drives via the
# existing `bench_dsv4_trace_http.py` HTTP probe.
#
# Usage:
#   ./scripts/bench_ab_post_build.sh                         # quick smoke
#   ./scripts/bench_ab_post_build.sh --full                  # full c=1/c=16 sweep
#   ./scripts/bench_ab_post_build.sh --baseline-ref <SHA>    # explicit baseline
#   ./scripts/bench_ab_post_build.sh --skip-int4-parity      # if model unavailable
#
# Env knobs (passed through):
#   INFER_PORT          — defaults to 8000
#   CUDA_HOME           — must point at toolkit >= 12.6 for __nv_fp8_e8m0
#   ARLE_CUDA_DISABLE_MARLIN_W4_FP8=1  — required while marlin_w4_fp8 needs newer ptxas
#
# Outputs:
#   docs/experience/wins/$(date -u +%F)-bench-post-build-{gap-b,gap-c,int4-kivi}.md
#   /tmp/arle-bench-summary.json
#
# Exit codes:
#   0 — all PASS
#   1 — at least one axis FAIL (regression > +1% or parity below floor)
#   2 — infrastructure failure (server didn't start, missing model, etc.)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

INFER_PORT="${INFER_PORT:-8000}"
INFER_HOST="${INFER_HOST:-127.0.0.1}"
FULL_SWEEP=0
SKIP_INT4_PARITY=0
BASELINE_REF=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --full) FULL_SWEEP=1; shift;;
    --baseline-ref) BASELINE_REF="$2"; shift 2;;
    --skip-int4-parity) SKIP_INT4_PARITY=1; shift;;
    -h|--help) sed -n '2,30p' "$0"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

if [[ -z "$BASELINE_REF" ]]; then
  BASELINE_REF="$(git rev-parse HEAD~5)"
  echo "[info] no --baseline-ref given; defaulting to HEAD~5=$BASELINE_REF"
fi

HEAD_SHA="$(git rev-parse --short HEAD)"
DATE_UTC="$(date -u +%F)"
SUMMARY_JSON="/tmp/arle-bench-summary-${HEAD_SHA}.json"
RESULTS=()
FAIL=0

probe_server() {
  curl -fsS --max-time 5 "http://${INFER_HOST}:${INFER_PORT}/health" >/dev/null 2>&1
}

run_bench() {
  local label="$1"; shift
  local out="/tmp/arle-bench-${label}-${HEAD_SHA}.json"
  echo "[bench] $label → $out"
  python3 scripts/bench_dsv4_trace_http.py \
    --host "$INFER_HOST" --port "$INFER_PORT" \
    --output-json "$out" "$@" 2>&1 | tail -20
  echo "$out"
}

emit_wins() {
  local axis="$1" delta_pct="$2" verdict="$3" data="$4"
  local out="docs/experience/wins/${DATE_UTC}-bench-post-build-${axis}.md"
  cat >"$out" <<EOF
# Post-build bench — ${axis} (HEAD=${HEAD_SHA} vs baseline=$(git rev-parse --short "$BASELINE_REF"))

## SLO-shape probed? — Y

## Verdict: ${verdict}

## Δ TPOT: ${delta_pct}%

## Anchor data

\`\`\`json
${data}
\`\`\`

## Refs

- Audit: \`docs/research/2026-05-28-arle-kernel-vs-sota-audit.md\`
- Generated by \`scripts/bench_ab_post_build.sh\` on $(date -u +%FT%TZ)
EOF
  echo "[wins] $out"
}

echo "== Step 1: verify build symbols =="
SYMBOLS_REQUIRED=(
  "dsv4_route_block_argmax"        # GAP-B
  "decode_attention_fp8_per_channel_k_partial_kernel"  # GAP-C-cheap (kernel name unchanged; pipeline now cp.async)
  "K_dynamic_scales"               # INT4 KIVI two-level-K parameter
)
BIN="${BIN:-/data01/build/arle/target/release/infer}"
if [[ ! -x "$BIN" ]]; then
  BIN="$(cargo build --release --features cuda,nccl -p infer --bin infer 2>&1 | tail -3 | head -1 || true; echo target/release/infer)"
fi
if [[ ! -x "$BIN" ]]; then
  echo "[fatal] infer binary not found"; exit 2
fi
for sym in "${SYMBOLS_REQUIRED[@]}"; do
  if strings "$BIN" 2>/dev/null | grep -q "$sym"; then
    echo "  ✓ $sym"
  else
    echo "  ✗ $sym MISSING — binary is stale"; FAIL=1
  fi
done
[[ $FAIL -eq 1 ]] && exit 1

echo
echo "== Step 2: start infer server (if not running) =="
if ! probe_server; then
  echo "[info] starting infer on :$INFER_PORT in background"
  "$BIN" serve --port "$INFER_PORT" >/tmp/arle-infer-server.log 2>&1 &
  SERVER_PID=$!
  trap 'kill $SERVER_PID 2>/dev/null || true' EXIT
  for i in {1..60}; do
    sleep 2
    probe_server && break
  done
  probe_server || { echo "[fatal] server didn't come up"; exit 2; }
fi

echo
echo "== Step 3: DSv4 decode TPOT (GAP-B + GAP-C-cheap) =="
GAP_BC_OUT="$(run_bench gap-bc --fanout 1)"
[[ $FULL_SWEEP -eq 1 ]] && GAP_BC_C16_OUT="$(run_bench gap-bc-c16 --fanout 16)"

DELTA_BC="$(jq -r '.dsv4_decode_p50_ms_delta_pct // "n/a"' "$GAP_BC_OUT" 2>/dev/null || echo "n/a")"
if [[ "$DELTA_BC" == "n/a" ]]; then
  echo "[warn] no delta_pct in bench output; emitting raw"
  emit_wins "gap-b-c" "n/a" "DATA-ONLY (no baseline comparison)" "$(cat "$GAP_BC_OUT" 2>/dev/null | head -100)"
else
  VERDICT="PASS"; (( $(echo "$DELTA_BC > 1" | bc -l) )) && VERDICT="FAIL (regression > 1%)" && FAIL=1
  (( $(echo "$DELTA_BC <= -3" | bc -l) )) && VERDICT="WIN (≥3% gain — matches audit projection)"
  emit_wins "gap-b-c" "$DELTA_BC" "$VERDICT" "$(jq '.' "$GAP_BC_OUT" 2>/dev/null | head -50)"
fi

echo
if [[ $SKIP_INT4_PARITY -eq 0 ]]; then
  echo "== Step 4: INT4 KIVI two-level-K parity vs BF16 reference =="
  if [[ -x infer/tests/kv_precision_parity.rs ]] || cargo test --release -p infer --features cuda \
       --test kv_precision_parity -- --list 2>/dev/null | grep -q int4; then
    KV_PARITY_PROMPTS=8 KV_PARITY_MAX_TOKENS=32 \
      cargo test --release -p infer --features cuda --test kv_precision_parity \
      -- --nocapture int4 2>&1 | tee /tmp/arle-int4-parity.log | tail -30
    MEAN_MATCH="$(grep -oE 'mean_match[ =:]+[0-9.]+' /tmp/arle-int4-parity.log | tail -1 | grep -oE '[0-9.]+' || echo 0)"
    VERDICT="PASS"
    (( $(echo "$MEAN_MATCH < 0.5" | bc -l) )) && VERDICT="FAIL (mean_match < 0.5; below PoC 0.094 ceiling not reached)" && FAIL=1
    (( $(echo "$MEAN_MATCH > 0.7" | bc -l) )) && VERDICT="WIN (mean_match > 0.7 — two-level-K closes most of INT8 gap)"
    emit_wins "int4-kivi-parity" "n/a-parity-metric" "$VERDICT (mean_match=$MEAN_MATCH)" "$(tail -30 /tmp/arle-int4-parity.log)"
  else
    echo "[skip] kv_precision_parity test not present; skip parity"
  fi
fi

echo
echo "== Summary =="
echo "HEAD: $HEAD_SHA"
echo "Baseline: $(git rev-parse --short "$BASELINE_REF")"
echo "GAP-B+C Δ TPOT: $DELTA_BC%"
[[ $SKIP_INT4_PARITY -eq 0 ]] && echo "INT4 KIVI mean_match: ${MEAN_MATCH:-n/a}"
echo "Wins entries written under docs/experience/wins/${DATE_UTC}-bench-post-build-*.md"
echo "Final verdict: $([[ $FAIL -eq 0 ]] && echo PASS || echo FAIL)"
exit $FAIL
